#!/bin/bash
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOCS_DIR="$SCRIPT_DIR/.."
REPO_DIR="$DOCS_DIR/.."

echo "--- Generating API docs ---"

# ── Python API docs (optional — requires sphinx + sphinx-markdown-builder) ──
if python3 -c "import sphinx; import sphinx_markdown_builder" 2>/dev/null; then
  PYTHON_SRC="$REPO_DIR/python/src/ducto"
  PYTHON_OUT="$DOCS_DIR/docs/python-api/reference"
  mkdir -p "$PYTHON_OUT" /tmp/ducto-sphinx /tmp/ducto-sphinx-out

  echo "[python] Running sphinx-apidoc..."
  python3 -m sphinx.ext.apidoc --separate --force -o /tmp/ducto-sphinx "$PYTHON_SRC"

  # Create an index.rst that pulls in the modules.rst generated by apidoc
  printf '%s\n' 'ducto API Reference' '""""""""""""""""""' '' '.. toctree::' '   :maxdepth: 2' '' '   modules' > /tmp/ducto-sphinx/index.rst

  echo "[python] Building markdown..."
  sphinx-build -b markdown -c "$SCRIPT_DIR" /tmp/ducto-sphinx /tmp/ducto-sphinx-out

  mkdir -p "$PYTHON_OUT"
  cp -r /tmp/ducto-sphinx-out/*.md "$PYTHON_OUT/" 2>/dev/null
  # Mark all generated files as plain Markdown with angle-bracket escaping
  # Sphinx output includes <factory> and TypeScript-style generics that MDX
  # misinterprets as JSX tags — escape them to HTML entities
  python3 -c "
import sys, os
root = sys.argv[1]
for dirpath, _dirnames, filenames in os.walk(root):
    for fn in filenames:
        if not fn.endswith('.md'):
            continue
        fp = os.path.join(dirpath, fn)
        with open(fp) as f:
            c = f.read()
        # Add format: md frontmatter if missing
        if not c.startswith('---'):
            c = '---\nformat: md\n---\n\n' + c
        # Escape angle brackets (JSX) and curly braces (JS expressions)
        # MDX interprets these as syntax even in plain Markdown files
        c = c.replace('<', '&lt;').replace('>', '&gt;')\
             .replace('{', '&#123;').replace('}', '&#125;')
        with open(fp, 'w') as f:
            f.write(c)
" "$PYTHON_OUT"
  echo "[python] Wrote $(ls "$PYTHON_OUT"/*.md 2>/dev/null | wc -l) files"
  rm -rf /tmp/ducto-sphinx /tmp/ducto-sphinx-out
else
  echo "[python] Skipped — sphinx/sphinx_markdown_builder not installed"
fi

# ── JS API docs (optional — requires typedoc) ──
TYPEDOC="$DOCS_DIR/node_modules/.bin/typedoc"
if [ -f "$TYPEDOC" ]; then
  JS_SRC="$REPO_DIR/javascript/src"
  JS_OUT="$DOCS_DIR/docs/javascript-api/reference"
  mkdir -p "$JS_OUT"

  echo "[javascript] Installing JS deps for typedoc..."
  cd "$REPO_DIR/javascript"
  if [ ! -d node_modules ]; then
    npm install --ignore-scripts --no-audit --no-fund --include=dev 2>&1 | tail -2
  fi

  echo "[javascript] Running typedoc..."
  rm -rf "$JS_OUT"
  "$TYPEDOC" \
    --plugin typedoc-plugin-markdown \
    --out "$JS_OUT" \
    --readme none \
    --hideBreadcrumbs \
    --hidePageHeader \
    src/index.ts

  # Mark all generated files as plain Markdown with angle-bracket escaping
  python3 -c "
import sys, os
root = sys.argv[1]
for dirpath, _dirnames, filenames in os.walk(root):
    for fn in filenames:
        if not fn.endswith('.md'):
            continue
        fp = os.path.join(dirpath, fn)
        with open(fp) as f:
            c = f.read()
        if not c.startswith('---'):
            c = '---\nformat: md\n---\n\n' + c
        c = c.replace('<', '&lt;').replace('>', '&gt;')
        with open(fp, 'w') as f:
            f.write(c)
" "$JS_OUT"
  echo "[javascript] Done — $(find "$JS_OUT" -name '*.md' | wc -l) files"
else
  echo "[javascript] Skipped — typedoc not installed in docs/node_modules"
fi

echo "--- API docs generation complete ---"
